image: python:3.11.6

pipelines:
  default:
    - parallel:
        - step:
            name: "Django Company API tests"
            caches:
              - pip
            script:
              - pip install --upgrade pip
              - pip install pipenv --upgrade
              - pipenv install --system
              - pytest api/django_udemy -s -v --durations=0
        - step:
            name: "Fibonacci tests"
            caches:
              - pip
            script:
              - pip install --upgrade pip
              - pip install pipenv --upgrade
              - pipenv install --system
              - export PYTHONPATH=$PYTHONPATH:/api/django_udemy
              - pytest fibonacci -s -v
