image: python:3.11.6

pipelines:
  default:
    - step:
        name: "Django Company API tests"
        caches:
          - pip
        script:
          - pip install --upgrade pip
          - pip install pipenv --upgrade
          - pipenv install --system
          - export PYTHONPATH=/api/django_udemy
          - export DJANGO_SETTINGS_MODULE="django_udemy.settings"
          - pytest api/django_udemy/tests -s -v --durations=0
