# Generated by Django 5.0.3 on 2024-03-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_application_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="application_link",
            field=models.URLField(blank=True),
        ),
    ]
